nav:
  - Home: index.md
  - Usage:
    - Getting Started: Usage/getting-started.md
    - Install: Usage/install.md
    - Usage: Usage/usage.md
    - Options: Usage/options.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
  font:
    text: Fira Code
    code: Fira Code
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: cyan
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: cyan
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/twhite96/static-gen-ruby
repo_name: twhite96/static-gen-ruby
site_name: Ruby Gen
site_author: Tiffany White
site_description: Documentation for a static site generator I built using Ruby.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.toc:
      anchorlink: true
      permalink: true
      permalink_title: On this page
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: python/name:pymdownx.superfences.fence_code_format